on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action steps
      id: hello
      uses: jtucholski/hello-world-javascript-action@master 
      with:
        who-to-greet: 'Ricky'
    - name: Get the output time
      run: echo The time was ${{ steps.hello.outputs.time }}"